### ISSUE TITLE
Table type ZMQBA_GUI_T_SUBSCREEN

### ISSUE THREAD

**Issue by larshp** [MDJoerg/MQBA#1]
Hi,
Currently abapGit does not support having DDIC objects refer to workbench objects, as DDIC objects are always activated first.

Suggest moving the table definition to interface `zif_mqba_gui_bl` instead of having it in DDIC.

Definition,
![image](https://user-images.githubusercontent.com/5888506/44783682-6d752e00-ab8b-11e8-9851-f7f3fba93647.png)

Error when activating,
![image](https://user-images.githubusercontent.com/5888506/44783801-cc3aa780-ab8b-11e8-9cda-18ac5d192570.png)

Suggested move,
![image](https://user-images.githubusercontent.com/5888506/44783760-a6150780-ab8b-11e8-8e91-93c50df5b1ea.png)

**Comment by MDJoerg** [comment]
i will check this. Thanks.
