### ISSUE TITLE
Node-RED switch nodes check string not boolean

### ISSUE THREAD

**Issue by gregorwolf** [MDJoerg/MQBA#3]
In your currently published Node-RED flow you check for the string value of msg.valid. That needs to be adjusted to check for the boolean:

![screen shot 2018-08-29 at 15 25 36](https://user-images.githubusercontent.com/2639535/44790603-08780300-aba0-11e8-9c42-cb89f0af7f1a.png)

**Comment by MDJoerg** [comment]
thanks. merged now.
