### ISSUE TITLE
Type "APC_CONNECT_OPTIONS" is unknown in NetWeaver 7.52

### ISSUE THREAD

**Issue by gregorwolf** [MDJoerg/MQBA#9]
I've just tried to import the project in my NetWeaver ABAP 7.52 Developer Edition. The activation fails with this error message:

Interface Section ZIF_MQBA_API_MQTT_PROXY
Type "APC_CONNECT_OPTIONS" is unknown.

Can you provide details of the type so I can search for an alternative?

**Comment by MDJoerg** [comment]
Hi Gregor,

this new type comes with the new mqtt package in abap stack 7.53. I will check if I can create an own z-Type for this.

Here is the DDIC structure for this.

![grafik](https://user-images.githubusercontent.com/41207683/52896990-2e857400-31cf-11e9-8339-7ebb99d901c0.png)

Thx 
Joerg

**Comment by MDJoerg** [comment]
Hi Gregor,

please check again. The unknown type APC_CONNECT_OPTIONS was replaced by an own type ZMQBA_API_S_APC_CONN_OPT with fix https://github.com/MDJoerg/MQBA/commit/aa0c504b11196f99c444661cba6bf771332645b4

Please confirm. I have no valid check environment at the moment.

Thx Joerg

**Comment by gregorwolf** [comment]
Now I was able to activate everything without issues.
